# Generated by Django 4.2.9 on 2024-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('phone_model', models.CharField(max_length=25)),
                ('at_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=12)),
                ('photo_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
