# Generated by Django 4.2.9 on 2024-01-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_name',
        ),
    ]
